name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: jcaporossi/ledger-starknet-app-builder:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build application
        run: cargo ledger nanos
      - name: Upload app binary
        uses: actions/upload-artifact@v3
        with: 
          name: elfs
          path: target/nanos/release/nano-app-starknet
